const ActionType={
    CHANGEUSERNAME:"CHANGEUSERNAME",
    ALLCOMPANY:"ALLCOMPANY",
    ALLSTUDENT:"ALLSTUDENT",
    GET_USER:"GET_USER",
    LOADCOMPANYPOST:"LOADCOMPANYPOST",
    LOADSTUDENTPOST:"LOADSTUDENTPOST",
    LOADHIREREQ:"LOADHIREREQ",
    LOADAPPLYREQ:"LOADAPPLYREQ"
}
export default ActionType;